# Site settings
title:       testing
author:      Adam Trexler
description: "code snippets, data, curiosity"
baseurl:     "/captains-log" 
url:         "https://ajtrexler.github.io" 

# Social Links
email:            adam.trexler@posteo.net
twitter_username: t_rexler
github_username:  ajtrexler

# Build settings
markdown: kramdown
permalink: pretty
