title: bottomless coffee & curiosity
description: code snippets, data, curiosity
author: Adam J. Trexler
github: https://github.com/ajtrexler
about:
disqus_shortname:
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-instagram
      link: "https://www.instagram.com/a_trexler/"
    - icon: fa-twitter
      link: "https://twitter.com/t_rexler"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/adam-trexler-14200549"


share:
  twitter_username: t_rexler


urls:
    - text: About Me
      url: /about/
    - text: Science
      url: https://www.adamtrexler.com
    - text: Github
      url: https://github.com/ajtrexler
    - text: XML Feed
      url: /feed.xml

url: "https://ajtrexler.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
